### ISSUE TITLE
import statements error of werkzeug

### ISSUE THREAD

**Issue by jayesh6297** [hjlarry/flask-redisboard#8]
line number 18 in redisboard.py should be 
```python
from werkzeug.utils import cached_property 
from werkzeug.urls import url_quote_plus, url_unquote_plus
```
and line number 1 in __init__.py should be 
```python
from werkzeug.urls import url_quote_plus
```

**Comment by hjlarry** [comment]
thanks!  the werkzeug version may cause this problem,  I`ll update it and the `setup.py` later
